// packages/grid/svelte/src/lib/components/FormControl.svelte
<script lang="ts">
  export let label: string;
  export let id: string;
  export let required = false;
  export let optional = false;
  export let disabled = false;
  export let error = '';
  export let hint = '';
  export let type = 'text';
  export let placeholder = '';
</script>

<div aria-disabled={disabled} class="space-y-2">
  <label for={id} class="flex gap-x-1">
    <span class="label">{label}</span>
    {#if required}
      <span class="required"> *</span>
    {:else if optional}
      <span class="optional"> (optional)</span>
    {/if}
  </label>
  {#if hint}
    <p class="hint">{hint}</p>
  {/if}
  <input {type} {id} {placeholder} class="w-full border border-gray-500" />
  {#if error}
    <p class="error">{error}</p>
  {/if}
</div>

<style lang="postcss">
  [aria-disabled='true'] {
    @apply opacity-50 cursor-not-allowed;
  }

  .required {
    @apply text-primary-600 text-xs relative;
  }

  .label {
    @apply text-sm font-roboto font-bold leading-normal text-gray-500;
  }

  .optional {
    @apply text-primary-600 italic font-normal text-xs leading-160;
  }

  .hint {
    @apply text-gray-500 font-normal text-sm leading-normal;
  }

  .error {
    @apply text-red-600 text-right;
  }

  input {
    @apply w-full border border-gray-300 p-3 rounded;
    @apply text-sm leading-normal font-normal font-roboto;
  }

  input::placeholder {
    @apply text-gray-300;
  }
</style>

// packages/grid/frontend/src/components/FormControl.tsx
import { forwardRef } from 'react'
import tw, { styled } from 'twin.macro'
import type {
  ReactElement,
  ForwardRefRenderFunction,
  InputHTMLAttributes,
  PropsWithRef,
} from 'react'

export type FormControlProps = {
  optional?: boolean
  label?: string
  hint?: string
  error?: string
} & InputProps &
  InputHTMLAttributes<HTMLInputElement>

interface InputProps {
  variant?: 'outline' | 'flushed' | 'filled'
  error?: boolean | string
  leftAddOnProps?: ReactElement
  rightAddOnProps?: ReactElement
}

export const Label = styled.label`
  ${tw`text-gray-500 text-sm font-bold`}
`

export const Input = styled.input(({ variant, error }: InputProps) => [
  variant === 'outline' && tw`border rounded p-3 items-center`,
  tw`focus:(ring-transparent outline-none ring ring-0)`,
  tw`hover:(filter)`,
  error && tw`border-red-500 focus:(shadow-focus-danger) hover:(drop-shadow-hover-danger)`,
  !error && tw`border-gray-300 focus:(shadow-focus) hover:(drop-shadow-hover)`,
  tw`focus-visible:(ring-0)`,
  tw`w-full`,
])

export const Hint = styled.div``

export const Error = styled(Hint)`
  ${tw`text-sm text-danger-600 text-right`}
`

export const FormControl = forwardRef<HTMLInputElement, PropsWithRef<FormControlProps>>(
  (props, ref) => {
    const {
      variant = 'outline',
      leftAddOnProps,
      rightAddOnProps,
      label,
      name,
      required,
      hint,
      error,
      optional,
      placeholder,
      type,
      ...rest
    } = props
    const inputProps = {
      ref,
      type,
      placeholder,
      required,
      variant,
      error,
      name,
      ...rest,
    }

    return (
      <div key={name} tw="flex flex-col gap-2">
        {label && (
          <Label htmlFor={name}>
            <span>{label}</span>
            {required && <span tw="text-primary-600"> *</span>}
            {optional && <span tw="font-normal italic text-primary-600 text-xs"> (optional)</span>}
          </Label>
        )}
        <Input id={name} {...inputProps} />
        {!error && hint && <Hint>{hint}</Hint>}
        {error && <Error>{error}</Error>}
      </div>
    )
  }
)
